repos:
    - repo: local
      hooks:
        - id: mypy
          name: mypy
          entry: mypy game.py
          language: system
        - id: pytest
          name: pytest
          entry: pytest
          language: system